  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

 

  [[main]]
  name = "Portfolio"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"

  [[main]]
  name = "About"
  weight = 150
  identifier = "about"
  url = "/about/"

  [[main]]
  name = "Accomplishments"
  weight = 500
  identifier = "accomplishments"

 

  [[main]]
  name = "Certifications"
  weight = 510
  identifier = "certifications"
  url = "/certifications/"
  parent = "accomplishments"

   [[main]]
  name = "Technologies"
  weight = 520
  identifier = "awards"
  url = "/awards/"
  parent = "accomplishments" 

   [[main]]
  name = "Blog"
  weight = 600
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "Contact"
  weight = 700
  identifier = "contact"
  url = "/contact/"

  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/imprint/"

